//Types for Login
export const LOGIN_REQUEST_REQUEST = 'LOGIN_REQUEST_REQUEST';
export const LOGIN_REQUEST_SUCCESS = 'LOGIN_REQUEST_SUCCESS';
export const LOGIN_REQUEST_FAILURE = 'LOGIN_REQUEST_FAILURE';
//Types for Logout
export const LOGOUT_REQUEST_REQUEST = 'LOGOUT_REQUEST_REQUEST';
export const LOGOUT_REQUEST_SUCCESS = 'LOGOUT_REQUEST_SUCCESS';
export const LOGOUT_REQUEST_FAILURE = 'LOGOUT_REQUEST_FAILURE';
//Types for Social Login
export const SOCIAL_LOGIN_REQUEST_REQUEST = 'SOCIAL_LOGIN_REQUEST_REQUEST';
export const SOCIAL_LOGIN_REQUEST_SUCCESS = 'SOCIAL_LOGIN_REQUEST_SUCCESS';
export const SOCIAL_LOGIN_REQUEST_FAILURE = 'SOCIAL_LOGIN_REQUEST_FAILURE';
//Types for Sign up
export const SIGNUP_REQUEST = 'SIGNUP_REQUEST';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_FAILURE = 'SIGNUP_FAILURE';

//Types for OTP Verification
export const OTP_VERIFY_REQUEST = 'OTP_VERIFY_REQUEST';
export const OTP_VERIFY_SUCCESS = 'OTP_VERIFY_SUCCESS';
export const OTP_VERIFY_FAILURE = 'OTP_VERIFY_FAILURE';

//Types for  forgot password
export const FORGOT_PASSWORD_REQUEST = 'FORGOT_PASSWORD_REQUEST';
export const FORGOT_PASSWORD_SUCCESS = 'FORGOT_PASSWORD_SUCCESS';
export const FORGOT_PASSWORD_FAILURE = 'FORGOT_PASSWORD_FAILURE';

//Types for reset password
export const RESET_PASSWORD_REQUEST = 'RESET_PASSWORD_REQUEST';
export const RESET_PASSWORD_SUCCESS = 'RESET_PASSWORD_SUCCESS';
export const RESET_PASSWORD_FAILURE = 'RESET_PASSWORD_FAILURE';

//Types for Walkthrough
export const SET_WALKTHROUGH_REQUEST = 'SET_WALKTHROUGH_REQUEST';
export const SET_WALKTHROUGH_SUCCESS = 'SET_WALKTHROUGH_SUCCESS';

//SET PROFILE IMAGE
export const SET_PROFILE_IMAGE = 'SET_PROFILE_IMAGE';
export const SET_PROFILE_IMAGE_REQUEST = 'SET_PROFILE_IMAGE_REQUEST';

//Exercixe Screen Status
export const SET_EXERCISE_SCREEN_REQUEST = 'SET_EXERCISE_SCREEN_REQUEST';
export const SET_EXERCISE_SCREEN = 'SET_EXERCISE_SCREEN';
// Set Exercise Item
export const SET_EXERCISE_ITEM_REQUEST = 'SET_EXERCISE_ITEM_REQUEST';
export const SET_EXERCISE_ITEM_SUCCESS = 'SET_EXERCISE_ITEM_SUCCESS';

//GET PROFILE
export const GET_PROFILE_REQUEST = 'GET_PROFILE_REQUEST';
export const GET_PROFILE_SUCCESS = 'GET_PROFILE_SUCCESS';
export const GET_PROFILE_FAILURE = 'GET_PROFILE_FAILURE';

//UPDATE PROFILE
export const UPDATE_PROFILE_REQUEST = 'UPDATE_PROFILE_REQUEST';
export const UPDATE_PROFILE_SUCCESS = 'UPDATE_PROFILE_SUCCESS';
export const UPDATE_PROFILE_FAILURE = 'UPDATE_PROFILE_FAILURE';

//Get Lifted Weight
export const GET_LIFTED_WEIGHT_REQUEST = 'GET_LIFTED_WEIGHT_REQUEST';
export const GET_LIFTED_WEIGHT_SUCCESS = 'GET_LIFTED_WEIGHT_SUCCESS';
export const GET_LIFTED_WEIGHT_FAILURE = 'GET_LIFTED_WEIGHT_FAILURE';

//Get Ongoing Events
export const GET_ONGOING_EVENTS_REQUEST = 'GET_ONGOING_EVENTS_REQUEST';
export const GET_ONGOING_EVENTS_SUCCESS = 'GET_ONGOING_EVENTS_SUCCESS';
export const GET_ONGOING_EVENTS_FAILURE = 'GET_ONGOING_EVENTS_FAILURE';

//Get Upcoming Events
export const GET_UPCOMING_EVENTS_REQUEST = 'GET_UPCOMING_EVENTS_REQUEST';
export const GET_UPCOMING_EVENTS_SUCCESS = 'GET_UPCOMING_EVENTS_SUCCESS';
export const GET_UPCOMING_EVENTS_FAILURE = 'GET_UPCOMING_EVENTS_FAILURE';

//JOIN TEAM EVENTS
export const JOIN_TEAM_EVENTS_REQUEST = 'JOIN_TEAM_EVENTS_REQUEST';
export const JOIN_TEAM_EVENTS_SUCCESS = 'JOIN_TEAM_EVENTS_SUCCESS';
export const JOIN_TEAM_EVENTS_FAILURE = 'JOIN_TEAM_EVENTS_FAILURE';

//JOIN  EVENTS
export const JOIN_EVENTS_REQUEST = 'JOIN_EVENTS_REQUEST';
export const JOIN_EVENTS_SUCCESS = 'JOIN_EVENTS_SUCCESS';
export const JOIN_EVENTS_FAILURE = 'JOIN_EVENTS_FAILURE';

//SET Upcoming
export const SET_UPCOMING_REQUEST = 'SET_UPCOMING_REQUEST';
export const SET_UPCOMING_EVENT = 'SET_UPCOMING_EVENT';

//Set Ongoing
export const SET_ONGOING_REQUEST = 'SET_ONGOING_REQUEST';
export const SET_ONGOING_EVENT = 'SET_ONGOING_EVENT';

//Get CARD LIST
export const GET_CARD_LIST_REQUEST = 'GET_CARD_LIST_REQUEST';
export const GET_CARD_LIST_SUCCESS = 'GET_CARD_LIST_SUCCESS';
export const GET_CARD_LIST_FAILURE = 'GET_CARD_LIST_FAILURE';

//ADD CARD
export const ADD_CARD_REQUEST = 'ADD_CARD_REQUEST';
export const ADD_CARD_SUCCESS = 'ADD_CARD_SUCCESS';
export const ADD_CARD_FAILURE = 'ADD_CARD_FAILURE';

//GET PRIVACY POLICY
export const GET_PRIVACY_POLICY_REQUEST = 'GET_PRIVACY_POLICY_REQUEST';
export const GET_PRIVACY_POLICY_SUCCESS = 'GET_PRIVACY_POLICY_SUCCESS';
export const GET_PRIVACY_POLICY_FAILURE = 'GET_PRIVACY_POLICY_FAILURE';

//GET FAQ's
export const GET_FAQ_REQUEST = 'GET_FAQ_REQUEST';
export const GET_FAQ_SUCCESS = 'GET_FAQ_SUCCESS';
export const GET_FAQ_FAILURE = 'GET_FAQ_FAILURE';

//GET TERMS & CONDITIONS
export const GET_TERMS_CONDITION_REQUEST = 'GET_TERMS_CONDITION_REQUEST';
export const GET_TERMS_CONDITION_SUCCESS = 'GET_TERMS_CONDITION_SUCCESS';
export const GET_TERMS_CONDITION_FAILURE = 'GET_TERMS_CONDITION_FAILURE';

//GET ACTIVITIES
export const GET_ACTIVITY_REQUEST = 'GET_ACTIVITY_REQUEST';
export const GET_ACTIVITY_SUCCESS = 'GET_ACTIVITY_SUCCESS';
export const GET_ACTIVITY_FAILURE = 'GET_ACTIVITY_FAILURE';

//GET FILTERED ACTIVITIES
export const GET_FILTERED_ACTIVITY_REQUEST = 'GET_FILTERED_ACTIVITY_REQUEST';
export const GET_FILTERED_ACTIVITY_SUCCESS = 'GET_FILTERED_ACTIVITY_SUCCESS';
export const GET_FILTERED_ACTIVITY_FAILURE = 'GET_FILTERED_ACTIVITY_FAILURE';

//CREATE CUSTOM EXERCISE
export const CUSTOM_EXERCISE_REQUEST = 'CUSTOM_EXERCISE_REQUEST';
export const CUSTOM_EXERCISE_SUCCESS = 'CUSTOM_EXERCISE_SUCCESS';
export const CUSTOM_EXERCISE_FAILURE = 'CUSTOM_EXERCISE_FAILURE';
//Pay With Debit
export const PAY_WITH_DEBIT_REQUEST = 'PAY_WITH_DEBIT_REQUEST';
export const PAY_WITH_DEBIT_SUCCESS = 'PAY_WITH_DEBIT_SUCCESS';
export const PAY_WITH_DEBIT_FAILURE = 'PAY_WITH_DEBIT_FAILURE';

//Pay With Google
export const PAY_WITH_SOCIAL_REQUEST = 'PAY_WITH_SOCIAL_REQUEST';
export const PAY_WITH_SOCIAL_SUCCESS = 'PAY_WITH_SOCIAL_SUCCESS';
export const PAY_WITH_SOCIAL_FAILURE = 'PAY_WITH_SOCIAL_FAILURE';

//*************************Exercise****************************
//GET FILTERED ACTIVITIES
export const GET_EXERCISE_REQUEST = 'GET_EXERCISE_REQUEST';
export const GET_EXERCISE_SUCCESS = 'GET_EXERCISE_SUCCESS';
export const GET_EXERCISE_FAILURE = 'GET_EXERCISE_FAILURE';

// CREATE EXERCISE WORKOUT
export const CREATE_EXERCISE_WORKOUT_REQUEST =
  'CREATE_EXERCISE_WORKOUT_REQUEST';
export const CREATE_EXERCISE_WORKOUT_SUCCESS =
  'CREATE_EXERCISE_WORKOUT_SUCCESS';
export const CREATE_EXERCISE_WORKOUT_FAILURE =
  'CREATE_EXERCISE_WORKOUT_FAILURE';

//*************************Filters****************************
//GET FILTERED ACTIVITIES
export const GET_FILTERED_EXERCISE_REQUEST = 'GET_FILTERED_EXERCISE_REQUEST';
export const GET_FILTERED_EXERCISE_SUCCESS = 'GET_FILTERED_EXERCISE_SUCCESS';
export const GET_FILTERED_EXERCISE_FAILURE = 'GET_FILTERED_EXERCISE_FAILURE';

export const SET_FILTERED_EXERCISE_REQUEST = 'SET_FILTERED_EXERCISE_REQUEST';
export const SET_FILTERED_EXERCISE_SUCCESS = 'SET_FILTERED_EXERCISE_SUCCESS';

//GET FILTERED ACTIVITIES
export const SET_CATEGORY_FILTERED_REQUEST = 'SET_CATEGORY_FILTERED_REQUEST';
export const SET_CATEGORY_FILTERED_SUCCESS = 'SET_CATEGORY_FILTERED_SUCCESS';
//SET BODY FILTERED
export const SET_BODY_FILTERED_REQUEST = 'SET_BODY_FILTERED_REQUEST';
export const SET_BODY_FILTERED_SUCCESS = 'SET_BODY_FILTERED_SUCCESS';

//SELECT BODY FILTERED
export const SELECT_CATEGORY_FILTER_REQUEST = 'SELECT_CATEGORY_FILTER_REQUEST';
export const SELECT_CATEGORY_FILTER_SUCCESS = 'SELECT_CATEGORY_FILTER_SUCCESS';

//SELECT CATEGORY FILTER
export const SELECT_BODY_FILTER_REQUEST = 'SELECT_BODY_FILTER_REQUEST';
export const SELECT_BODY_FILTER_SUCCESS = 'SELECT_BODY_FILTER_SUCCESS';

//RECENT SEARCHES
export const SET_RECENT_SEARCHES_REQUEST = 'SET_RECENT_SEARCHES_REQUEST';
export const SET_RECENT_SEARCHES_SUCCESS = 'SET_RECENT_SEARCHES_SUCCESS';
