export const fontsFamily = {
  comorfaBold: 'comfortaBold',
  comorfaLight: 'comfortaBold',
  comorfaRegular: 'comfortaRegular',
  OpenSans_Bold: 'OpenSans-Bold',
  OpenSans_BoldItalic: 'OpenSans-BoldItalic',
  OpenSans_ExtraBold: 'OpenSans-ExtraBold',
  OpenSans_ExtraBoldItalic: 'OpenSans-ExtraBoldItalic',
  OpenSans_Italic: 'OpenSans-Italic',
  OpenSans_Light: 'OpenSans-Light',
  OpenSans_LightItalic: 'OpenSans-LightItalic',
  OpenSans_Medium: 'OpenSans-Medium',
  OpenSans_MediumItalic: 'OpenSans-MediumItalic',
  OpenSans_Regular: 'OpenSans-Regular',
  OpenSans_SemiBold: 'OpenSans-SemiBold',
  OpenSans_SemiBoldItalic: 'OpenSans-SemiBoldItalic',
};
