import {Platform, StatusBar, StyleSheet} from 'react-native';
import {WP, size, family, colors} from '../../../shared/exporter';

const styles = StyleSheet.create({
  main: {
    flex: 1,
    backgroundColor: 'white',
    paddingTop: Platform.OS === 'android' ? StatusBar.currentHeight : 0,
  },
  contentContainer: {
    marginHorizontal: WP('5'),
    flex: 1,
  },
  headerText: {
    fontSize: size.h6,
    color: colors.b7,
    fontFamily: family.OpenSans_Bold,
  },
  calculationContainer: {
    width: '100%',
    backgroundColor: colors?.white,
    borderRadius: 40,
    shadowColor: '#000',
    shadowOffset: {width: 0, height: 10},
    shadowRadius: 3.84,
    shadowOpacity: 0.1,
    elevation: 5,
    top: 10,
    borderColor: 'transparent',
    borderWidth: 1,
  },
  calculationInnerContainer: {
    width: '85%',
    alignSelf: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  iconAndTextContainer: {
    justifyContent: 'center',
    padding: 20,
    alignItems: 'center',
  },
  count: {
    fontSize: size.large,
    fontFamily: family.OpenSans_Bold,
    color: colors?.b1,
    marginTop: 5,
  },
  category: {
    fontSize: size.small,
    fontFamily: family.OpenSans_Light,
    color: '#323232',
  },
  history: {
    color: colors.p1,
  },
  achievements: {
    color: colors.b1,
    fontFamily: family?.OpenSans_Medium,
  },
  logoutBtn: {
    bottom: 10,
    alignSelf: 'center',
    marginTop: '5%',
    padding: 10,
    backgroundColor: colors.g10,
    borderRadius: 10,
    width: '90%',
    justifyContent: 'center',
    alignItems: 'center',
  },
  txtContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: '5%',
  },
  dropDownContainer: {
    width: '100%',
    marginTop: '10%',
    borderRadius: 5,
    borderColor: colors.g10,
    borderWidth: 1,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  icon: {
    height: 30,
    width: 30,
    resizeMode: 'contain',
  },
  title: {
    fontFamily: family.Poppins_Medium,
    fontSize: size.medium,
    marginStart: '5%',
  },
  innerContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    marginStart: '3%',
  },
  dropDownItemsContianer: {
    borderTopColor: 'transparent',
    borderColor: colors.g8,
    borderWidth: 1,
    fontSize: size.small,
    color: colors.b1,
    fontFamily: family.OpenSans_Bold,
  },
  dropDownStyle: {
    width: '100%',
    borderColor: 'transparent',
  },
  placeholder: {
    fontSize: size.xsmall,
    color: colors.g1,
    fontFamily: family.OpenSans_Regular,
  },
  triangle: {
    width: 0,
    height: 0,
    backgroundColor: 'transparent',
    borderStyle: 'solid',
    borderLeftWidth: 5,
    borderRightWidth: 5,
    borderBottomWidth: 5,
    borderLeftColor: 'transparent',
    borderRightColor: 'transparent',
    borderBottomColor: colors.b1,
    marginStart: '5%',
  },
  iconAndText: {
    width: '25%',
    alignItems: 'center',
    marginRight: 10,
  },
  innerIconAndText: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  btnContainer: {
    marginVertical: WP('10'),
    backgroundColor: colors.p1,
    alignItems: 'center',
    padding: WP('5'),
    width: WP('90'),
    borderRadius: 10,
    shadowOffset: {
      width: 0,
      height: 4,
    },
    shadowColor: colors.shadowColor,
    shadowOpacity: 0.3,
    shadowRadius: 4.65,
    elevation: 8,
  },
  secondTitle: {
    fontSize: size.xlarge,
    color: colors.white,
    fontFamily: family.OpenSans_Bold,
    textAlign: 'center',
  },
  description: {
    fontSize: size.large,
    color: colors.white,
    fontFamily: family.OpenSans_Medium,
    textAlign: 'center',
    marginTop: '2%',
  },
  modeBtn: {
    width: WP('40'),
    height: WP('10'),
    borderColor: colors.white,
    borderWidth: 1,
    borderRadius: 20,
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: '10%',
  },
  buttonContainer: {
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: '10%',
  },
  dropdown: {
    width: '100%',
    height: 50,
    paddingHorizontal: 8,
  },
  label: {
    position: 'absolute',
    backgroundColor: 'white',
    left: 22,
    top: 8,
    zIndex: 999,
    paddingHorizontal: 8,
    fontSize: 12,
  },
  placeholderStyle: {
    color: colors?.g1,
  },
  selectedTextStyle: {
    fontFamily: family.Poppins_Medium,
    color: colors?.p1,
    fontSize: size.xxsmall,
  },
  iconStyle: {
    width: 20,
    height: 20,
  },
  inputSearchStyle: {
    height: 40,
    fontSize: 16,
  },
});

export default styles;
